### ISSUE TITLE
Use for databinding too?

### ISSUE THREAD

**Issue by ConorGarry** [Zhuinden/ViewBindingExample#4]
Hi Gabor, I slightly re-purposed this to use for databinding too, the only difference being the replacement of `ViewBinding` with `ViewDataBinding`.
It has been working perfectly apart from one issue, which you had also address on the medium post [here](https://medium.com/p/26777f565683/responses/show)

When using navigation component, replace is always used instead of add, so my Fragment view gets destroyed. When I navigate back to it, my binding doesn't work as it had been destroyed too.

Was I being too ambitious in thinking it would be Ok to use for Databinding?
Is there a way to manually recreate the binding when re-creating the View?

Thanks. 

Full example in case I've missed anything.

```kotlin
class FragmentViewBindingDelegate<T : ViewDataBinding>(
        val fragment: Fragment,
        val viewBindingFactory: (View) -> T
) : ReadOnlyProperty<Fragment, T> {
    private var binding: T? = null

    init {
        fragment.lifecycle.addObserver(object : DefaultLifecycleObserver {
            override fun onCreate(owner: LifecycleOwner) {
                fragment.viewLifecycleOwnerLiveData.observe(fragment, Observer {
                    it.lifecycle.addObserver(object : DefaultLifecycleObserver {
                        override fun onDestroy(owner: LifecycleOwner) {
                            binding = null
                        }
                    })
                })
            }
        })
    }

    override fun getValue(thisRef: Fragment, property: KProperty<*>): T {
        val binding = binding
        if (binding != null) {
            return binding
        }

        val lifecycle = fragment.viewLifecycleOwner.lifecycle
        if (!lifecycle.currentState.isAtLeast(Lifecycle.State.INITIALIZED)) {
            throw IllegalStateException("Should not attempt to get bindings when Fragment views are destroyed.")
        }

        return viewBindingFactory(thisRef.requireView()).also { this@FragmentViewBindingDelegate.binding = it }
    }
}

fun <T : ViewDataBinding> Fragment.dataBinding(viewBindingFactory: (View) -> T) =
        FragmentViewBindingDelegate(this, viewBindingFactory)
```

**Comment by ConorGarry** [comment]
Ok I figured it out 🤦 

It's because I was binding the ViewModel and Lifecycle in an `apply` scoped function which wasn't being called when Fragment View was being recreated.
So it seems it is Ok to use for Databinding as well as ViewBinding.

**Comment by Zhuinden** [comment]
It would have been odd if not, the viewLifecyleOwner's lifecycle SHOULD recreate the binding on back navigation when the view is recreated. :+1:
